create_ip -name ila -vendor xilinx.com -library ip -version 6.2 -module_name ila_0
set_property -dict [list CONFIG.C_PROBE19_WIDTH {32} CONFIG.C_PROBE18_WIDTH {32} \
CONFIG.C_PROBE17_WIDTH {32} CONFIG.C_PROBE16_WIDTH {32} CONFIG.C_PROBE15_WIDTH {32} \
CONFIG.C_PROBE14_WIDTH {32} CONFIG.C_PROBE13_WIDTH {32} CONFIG.C_PROBE12_WIDTH {32} \
CONFIG.C_PROBE11_WIDTH {32} CONFIG.C_PROBE10_WIDTH {8} CONFIG.C_PROBE9_WIDTH {8} \
CONFIG.C_PROBE8_WIDTH {8} CONFIG.C_PROBE7_WIDTH {8} CONFIG.C_PROBE6_WIDTH {8} \
CONFIG.C_NUM_OF_PROBES {20} CONFIG.C_EN_STRG_QUAL {1} CONFIG.C_INPUT_PIPE_STAGES {2} \
CONFIG.C_ADV_TRIGGER {true} CONFIG.ALL_PROBE_SAME_MU {FALSE} CONFIG.C_PROBE0_MU_CNT {4} \
CONFIG.C_PROBE1_MU_CNT {4} CONFIG.C_PROBE2_MU_CNT {4} CONFIG.C_PROBE3_MU_CNT {4} \
CONFIG.C_PROBE4_MU_CNT {4} CONFIG.C_PROBE5_MU_CNT {4} CONFIG.C_PROBE6_MU_CNT {4} \
CONFIG.C_PROBE7_MU_CNT {4} CONFIG.C_PROBE8_MU_CNT {4} CONFIG.C_PROBE9_MU_CNT {4} \
CONFIG.C_PROBE10_MU_CNT {4} CONFIG.C_PROBE11_MU_CNT {4} CONFIG.C_PROBE12_MU_CNT {4} \
CONFIG.C_PROBE13_MU_CNT {4} CONFIG.C_PROBE14_MU_CNT {4} CONFIG.C_PROBE15_MU_CNT {4} \
CONFIG.C_PROBE16_MU_CNT {4} CONFIG.C_PROBE17_MU_CNT {4} CONFIG.C_PROBE18_MU_CNT {4} \
CONFIG.C_PROBE19_MU_CNT {4}] [get_ips ila_0]

generate_target all [get_files  ./../genesys-systolic/source/xilinx_macros/ila_0.xci]
